import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import { Fira_Code } from "next/font/google";
// @ts-ignore
import "./globals.css";
import IDEBox from "@/components/IDEBox/IDEBox";
import GradientCanvas from "@/components/GradientBackground/GradientCanvas";

const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
});

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${instrumentSans.variable} ${firaCode.variable} antialiased`}
      >
        <main className="flex flex-grow w-screen h-screen it items-center justify-center p-0 sm:p-10">
          <IDEBox>
            {children}
          </IDEBox>
          <GradientCanvas />
        </main>
      </body>
    </html>
  );
}
